# Generated by Django 2.2.6 on 2019-10-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191023_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(blank=True, related_name='_category_parent_category_+', to='app.Category'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer',
            field=models.ManyToManyField(blank=True, related_name='_employee_employer_+', to='app.Employee'),
        ),
    ]
