# Generated by Django 2.2.6 on 2019-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191023_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_employee_employee_+', to='app.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_employee_employer_+', to='app.Employee'),
        ),
    ]
