# Generated by Django 2.2.6 on 2019-10-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191023_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_category_parent_category_+', to='app.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_category_subcategory_+', to='app.Category'),
        ),
    ]
