# Generated by Django 2.2.4 on 2019-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191023_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='description',
        ),
        migrations.RemoveField(
            model_name='local',
            name='name',
        ),
        migrations.AddField(
            model_name='local',
            name='campus',
            field=models.CharField(default='Praia Vermelha', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='unit',
            field=models.CharField(default='IC', max_length=100),
            preserve_default=False,
        ),
    ]
